name: cargopro_frontend
description: CargoPro Frontend Internship Assignment - Flutter + GetX + Firebase + REST API
publish_to: "none"
version: 1.0.0
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.5
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
